---
title: "Var estimation with using Garch family"
author: "ElgunIsmayilov"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Importing necessary libraries
```{r libraries}
library(tidyverse)
library(zoo)
library(xts)
library(quantmod)
library(imputeTS)
library(tseries)

```

# Import the data

```{r data}
# Define the tickers
Dow_Jones <- getSymbols("^DJI",src = "yahoo",from = "2019-01-01", to = "2023-01-01",auto.assign = FALSE)
Tmsc <- getSymbols("TSM",src = "yahoo",from = "2019-01-01", to = "2023-01-01",auto.assign = FALSE)
Pound <- getSymbols("GBPUSD=X",src = "yahoo",from = "2019-01-01", to = "2023-01-01",auto.assign = FALSE)
Silver <- getSymbols("SI=F",src = "yahoo",from = "2019-01-01", to = "2023-01-01",auto.assign = FALSE)
BNB<- na_locf(getSymbols("BNB-USD",src = "yahoo",from = "2019-01-01", to = "2023-01-01",auto.assign = FALSE))
# Extract the adjusted closing prices for each symbol



```

```{r}
Dow_Jones$r <- diff.xts(log(na_locf(Dow_Jones$DJI.Adjusted)))
Tmsc$r <- diff.xts(log(na_locf(Tmsc$TSM.Adjusted)))
Pound$r <- diff.xts(log(na_locf(Pound$GBPUSD.X.Adjusted)))
Silver$r <- diff.xts(log(na_locf(Silver$SI.F.Adjusted)))
BNB$r <- diff.xts(log(na_locf(BNB$BNB.USD.Adjusted)))
print(Tmsc$r)
```





```{r}

# Assuming you have xts time series objects for each asset (Dow_Jones, Tmsc, Pound, Silver, BNB)

# Calculate the combined returns of all assets
combined_returns <- Dow_Jones$r + Tmsc$r + Pound$r + Silver$r + BNB$r

# Calculate the portfolio returns with equal weights
weight <- 0.2
portfolio_returns <- combined_returns * weight

# Convert the xts object to a data frame
portfolio_df <- data.frame(date = index(combined_returns), portfolio_returns = coredata(portfolio_returns))
# Print the portfolio data frame
print(portfolio_df)



```








```{r}



# Create a scatter plot
ggplot(portfolio_xts, aes(x =portfolio_df$date , y = portfolio_df$r )) +
  geom_point() +
  labs(title = "Portfolio Daily Returns",
       x = "Date",
       y = "Daily Return")



```

```{r}
# Distribution plot
distribution_plot <- ggplot(portfolio_df, aes(x = portfolio_df$r)) +
  geom_histogram(binwidth = 0.01, fill = "skyblue", color = "black") +
  labs(title = "Distribution of Portfolio Returns",
       x = "Portfolio Return",
       y = "Frequency")

# Show the distribution plot
print(distribution_plot)


```
Pot of returns
```{r}
plot(portfolio_df$date,portfolio_df$r,type = "l",col="red",lwd=1,main="Return of Portfolio")
```

```{r}

adf.test(portfolio_df$r[-1])
```


Plot of ACF for returns 
```{r}
acf(portfolio_df$r,lag.max = 36, na.action = na.pass,col="darkblue",lwd=7,main="ACF of Portfolio returns")

acf(portfolio_df$r, lag.max = 36, na.action = na.pass, ylim = c(-0.2, 0.2),
    col = "darkblue", lwd = 7, main = "ACF of Portfolio returns")
```
Plot of ACF for **squared returns**.
```{r}
acf(portfolio_df$r^2,lag.max = 100,na.action = na.pass,col="darkblue",lwd=7,main="ACF of Portfolio squared returns")
acf(portfolio_df$r^2,lag.max = 100,na.action = na.pass,
    ylim= c(0, 0.5),col="darkblue",lwd=7,main="CF of Portfolio squared returns")

```
Testing for ARCH effects.
```{r}
ArchTest(portfolio_df$r,lags = 5)
durbinWatsonTest(lm(portfolio_df$r^2 ~ 1),max.lag = 5)


```

Normality test
```{r}
basicStats((portfolio_df$r))
hist(portfolio_df$r, prob=T, breaks = 40)
curve(dnorm(x, mean(portfolio_df$r, na.rm= T),
            sd=sd(portfolio_df$r, na.rm = T)),
      col="darkblue",lwd=2, add=TRUE)

jarque.bera.test(na.omit(portfolio_df$r))
durbinWatsonTest(lm(portfolio_df$r ~ 1), max.lag = 5)


```

Standardization of returns.

```{r}
portfolio_df$stan <-(portfolio_df$r-mean(portfolio_df$r, na.rm=T))/ sd(portfolio_df$r, na.rm = T)

tail(portfolio_df$stan)

```
Histogram of standart return
```{r}
hist(portfolio_df$stan, prob=T, breaks = 40)
curve(dnorm(x, mean(portfolio_df$stan, na.rm= T),
            sd=sd(portfolio_df$stan, na.rm = T)),
      col="darkblue",lwd=2, add=TRUE)

```
Descriptive statistics of standardized returns .
```{r}
basicStats(portfolio_df$stan)

```
1% empirical quantile

```{r}
quantile(portfolio_df$stan,0.01, na.rm=T)

```
For comparison: 1% quantile of standard normal distribution
```{r}
qnorm(0.01,0,1)

```